name: Login to Docker, build, tag, push and Azure Deploy
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
    
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Build database image
          run: |
            docker build -t biseras/postgres ./postgres
            
        - name: Build backend image
          run: |
            docker build -t biseras/film ./backend
            
        - name: Docker database tag
          run: |
            docker tag biseras/postgres biseras/postgres
            
        - name: Docker backend tag
          run: |
            docker tag biseras/film biseras/film
        
        - name: Docker push database image
          run: |
            docker push biseras/postgres
        
        - name: Docker push backend image
          run: |
            docker push biseras/film






# name: Docker Build and Push to DockerHub

# on:
#   push:
#     # branches-ignore: [master, main]
#     # Remove the line above to run when pushing to master
#   pull_request:
#     branches: [master, main]

# ###############
# # Set the Job #
# ###############
# jobs:
           
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Test
#         run: |
#           pwd
#           ls
#       -
#          name: Build and push
#          uses: docker/build-push-action@v2
#          with:
#            context: Film
#            push: true
#            tags: biseras/film:latest
#       -
#          name: Build and push 2
#          uses: docker/build-push-action@v2
#          with:
#            push: true
#            tags: biseras/postgres:latest
           
           
           
           
           
      
#   build: 
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push 2
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: biseras/postgres:latest
      
